#!/usr/bin/env python3
"""
gen_pet_sprites.py - Convert pet animal PNGs into banked C sprite data.

Reads animal PNGs from assets/sprites-and-tilesets/pet-sprites/ and
produces src/pet_sprites.c with 2bpp tile data for all pets.

Each pet has 8 tiles (2 frames x 4 quadrants = 128 bytes).
Sprites are front-facing only; no directional variants.

Asset source: https://gamebowgames.itch.io/16x16-small-animals-for-use-with-gbstudio
"""

import os
import sys
from PIL import Image

PET_DIR = "assets/sprites-and-tilesets/pet-sprites"
OUTPUT_C = "src/pet_sprites.c"

# PNG pixel colors -> 2bpp color index (same mapping as gen_all_sprites.py)
COLOR_MAP = {
    (0, 255, 0): 0,        # chroma green = transparent
    (224, 248, 207): 1,     # lightest
    (134, 192, 108): 2,     # mid
    (7, 24, 33): 3,         # darkest
    (0, 0, 0): 3,           # pure black fallback
}


def pixel_to_color_idx(img, x, y):
    px = img.getpixel((x, y))
    rgb = (px[0], px[1], px[2])
    idx = COLOR_MAP.get(rgb)
    if idx is None:
        best, best_dist = 0, 999999
        for ref, ci in COLOR_MAP.items():
            d = sum((a - b) ** 2 for a, b in zip(rgb, ref))
            if d < best_dist:
                best_dist, best = d, ci
        return best
    return idx


def extract_tile_8x8(img, px_x, px_y):
    tile = []
    for row in range(8):
        lo, hi = 0, 0
        for col in range(8):
            cidx = pixel_to_color_idx(img, px_x + col, px_y + row)
            bit = 7 - col
            if cidx & 1:
                lo |= (1 << bit)
            if cidx & 2:
                hi |= (1 << bit)
        tile.append(lo)
        tile.append(hi)
    return tile


def extract_frame_16x16(img, fx, fy):
    tiles = []
    tiles.extend(extract_tile_8x8(img, fx, fy))          # TL
    tiles.extend(extract_tile_8x8(img, fx + 8, fy))      # TR
    tiles.extend(extract_tile_8x8(img, fx, fy + 8))      # BL
    tiles.extend(extract_tile_8x8(img, fx + 8, fy + 8))  # BR
    return tiles


def convert_pet_sheet(filepath):
    img = Image.open(filepath).convert("RGBA")
    w, h = img.size

    if w == 32 and h == 16:
        # Side-by-side: frame 0 at (0,0), frame 1 at (16,0)
        positions = [(0, 0), (16, 0)]
    elif w == 16 and h == 32:
        # Stacked: frame 0 at (0,0), frame 1 at (0,16)
        positions = [(0, 0), (0, 16)]
    else:
        raise ValueError(f"Unexpected pet sprite size: {w}x{h} in {filepath}")

    all_tiles = []
    for fx, fy in positions:
        all_tiles.extend(extract_frame_16x16(img, fx, fy))

    assert len(all_tiles) == 128, f"Expected 128 bytes, got {len(all_tiles)}"
    return all_tiles


def format_c_array(data, indent="    "):
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"{indent}{hex_vals}")
    return ",\n".join(lines)


def main():
    files = sorted(
        f for f in os.listdir(PET_DIR) if f.endswith(".png")
    )
    if not files:
        print(f"ERROR: No .png files found in {PET_DIR}")
        sys.exit(1)

    print(f"Found {len(files)} pet sprites:")
    for f in files:
        print(f"  {f}")

    pets = []
    for f in files:
        path = os.path.join(PET_DIR, f)
        data = convert_pet_sheet(path)
        name = os.path.splitext(f)[0]
        pets.append((name, data))
        print(f"  Converted {f}: {len(data)} bytes")

    num_pets = len(pets)
    total_bytes = num_pets * 128

    with open(OUTPUT_C, "w") as out:
        out.write("/*\n")
        out.write(" * pet_sprites.c -- 2bpp sprite data for companion pets.\n")
        out.write(f" * {num_pets} pets, 8 tiles each (2 frames x 4 quadrants).\n")
        out.write(f" * {total_bytes} bytes total, ROM bank 10.\n")
        out.write(" * Generated by tools/gen_pet_sprites.py -- do not edit.\n")
        out.write(" */\n\n")
        out.write("#include <gb/gb.h>\n")
        out.write("#include <gbdk/platform.h>\n")
        out.write('#include "pet_sprites.h"\n\n')
        out.write("#pragma bank 10\n\n")

        out.write(f"static const UINT8 all_pet_data[{total_bytes}] = {{\n")
        for i, (name, data) in enumerate(pets):
            out.write(f"\n    /* Pet {i}: {name} (offset {i * 128}) */\n")
            out.write(format_c_array(data))
            if i < num_pets - 1:
                out.write(",\n")
            else:
                out.write("\n")
        out.write("};\n\n")

        out.write("void pet_sprites_load_pet(UINT8 idx) NONBANKED {\n")
        out.write("    UINT8 old_bank = _current_bank;\n")
        out.write(f"    if (idx >= {num_pets}u) idx = 0;\n")
        out.write("    SWITCH_ROM_MBC1(10);\n")
        out.write(f"    set_sprite_data(PET_SPRITE_BASE, PET_SPRITE_TILES,\n")
        out.write(f"                    all_pet_data + (UINT16)idx * 128u);\n")
        out.write("    SWITCH_ROM_MBC1(old_bank);\n")
        out.write("}\n\n")

        out.write("void pet_sprites_load_preview(UINT8 idx) NONBANKED {\n")
        out.write("    UINT8 old_bank = _current_bank;\n")
        out.write(f"    if (idx >= {num_pets}u) idx = 0;\n")
        out.write("    SWITCH_ROM_MBC1(10);\n")
        out.write("    set_bkg_data(132u, 4u, all_pet_data + (UINT16)idx * 128u);\n")
        out.write("    SWITCH_ROM_MBC1(old_bank);\n")
        out.write("}\n")

    print(f"\nWrote {OUTPUT_C}: {num_pets} pets, {total_bytes} bytes")


if __name__ == "__main__":
    main()
